### ISSUE TITLE
parse_mode="HTML"

### ISSUE THREAD

**Issue by Jakgab617** [Dextroz/RSS_Feederbot#4]
Hi,
When I try to make this change in context.bot.send_message, I am getting an error.

**Comment by ghost** [comment]
Hi, can you post the exact error that is occuring. Please ensure you redact anything which is personally identifiable from the error message.

From the issue title. Altering the `parse_mode` parameter to `HTML` is **highly** likely cause an error. The bots function **feed_to_md** converts the RSS feed content into `Markdown` format hence why the `parse_mode` parameter is set to `Markdown`. Altering it to HTML would produce an error as it would be trying to parse the `Markdown` content as HTML. https://github.com/Dextroz/RSS_Feederbot/blob/06690bf7f9f4bc2c68906d31ebf86ae8ece21d14/bot.py#L33

**Comment by Jakgab617** [comment]
Hello, thanks for the prompt response. I do realize that Line 33 is for the markdown.  I just wanted to try if I can change the output to HTML as there is the html2text option for images and links.  I was pulling the summary of the feed. Otherwise, the bot works as it should be. But here's the error:

Traceback (most recent call last):
  File "/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 270, in tick
    job.run(self._dispatcher)
  File "/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 399, in run
    self.callback(CallbackContext.from_job(self, dispatcher))
  File "/RSS_Feederbot/bot.py", line 95, in check_feeds
    context.bot.send_message(chat_id="6******4", text=rss_msg, parse_mode="HTML", disable_web_page_preview="True")
  File "/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/lib/python3.7/site-packages/telegram/bot.py", line 258, in send_message
    timeout=timeout, **kwargs)
  File "/lib/python3.7/site-packages/telegram/bot.py", line 123, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/lib/python3.7/site-packages/telegram/utils/request.py", line 238, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: unsupported start tag "br/" at byte offset 27
>>> 

*** Line 45 & 46 is already set to False.

**Comment by ghost** [comment]
Hi,
Would you be able to produce the output of the variable rss_msg.
It should contain HTML content as well as text content. 

This issue could also be related to https://github.com/python-telegram-bot/python-telegram-bot/issues/682

**Comment by Jakgab617** [comment]
Hi,
The message generated is the linked article title. There is no problem with your bot. It actually does what it says, a markdown feed. It is only when I try to make the changes to have a full article html output that I got stuck. If I make it into a full article, output generates text that includes codes like <br> etc and links not hyperlinked. I might try again this weekend and update you.

**Comment by dbrennand** [comment]
There has been no activity on this for sometime. I am closing this issue. If you are still experiencing this issue. Please re-open it.
